### PR TITLE
Publish to npm

### PR DESCRIPTION
**Pull request by lukepearson**
This change would add following actions on every merge into master which comes from a branch containing the word 'release':
* Increment the patch version
* Publish to npm

We would need to add a `NPM_TOKEN` secret if there isn't one already

I've given it a try on a [fork](https://github.com/lukepearson/nhsuk-react-components-extensions/runs/1566834131), with the dry run option enabled, it seems to work alright. Let me know what you think!

### CODE REVIEW

**Comment by simonireilly** [comment]
This looks ace.

Would be good to know the desired workflow.

1. We create a release branch, and that release is published to NPM **(current)**
2. We create a release tag and that release tag will publish to NPM

I prefer 2 since the user is acting with publish intent, this I think would look like:

```yaml
name: CD Build and Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Yarn Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Jest Tests
        run: yarn test:ci
      - name: Dist Build
        run: yarn build:dist
      - name: Lib Build
        run: yarn build:lib
      - name: Compile Styles
        run: yarn build:styles
      - name: Set Version to Release Tag Name
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "CI"
          yarn version --new-version ${{ github.event.release.tag_name }}
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy Storybook
        run: yarn storybook-to-ghpages --ci
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

Another benefit is you can just create any release you want e.g. `tag_name: 1.2.7.canary-2` in the GitHub UI, then it will be published to NPM on that tag :+1:

@Tomdango and @lukepearson what do you think?

**Comment by Tomdango** [comment]
This looks good to me, I'm back working tomorrow but might get a chance to look at this tonight and add in the NPM secrets to do a test run.
Just a slight side note - if a package is marked as alpha or beta (i.e. 1.2.7.beta-1) is there a way of passing in an NPM tag? Or would the new "beta" version replace the current "main" version?

**Comment by simonireilly** [comment]
Looks like we can get that from the action used: https://github.com/JS-DevTools/npm-publish#input-parameters

```
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "beta"
```

Default is "latest" :+1:

**Comment by Tomdango** [comment]
Looking at this again, I may have found an issue - we aren't checking for the version in package.json against the NPM repository - for example, if we wanted to bump up a minor version (i.e. to 1.6.0) we'd have to run a `yarn version` locally and then push up the changes. Then when we hit the release, it runs an additional `yarn version --patch` which would end up releasing version `1.6.1` and never `1.6.0` - and the versions in dev wouldn't be updated. Also we'd need to do a `git push` at the end of the script as well, as that'll push the new package version to the main branch

**Comment by lukepearson** [comment]
Good point, although if we use `yarn version --preminor` locally, then it will start at -0, and then get bumped up to 0 in CI, so we just have to remember to use that 
image

To get the versions in dev updated don't we then just have to pull from master? Using yarn to bump the version will automatically commit the version change in that package.json to the repository

**Comment by kevinkuszyk** [comment]
@lukepearson @Tomdango whilst this looks good, how do you feel about following the same pattern as the main repo, when we publish to npm when tags are pushed?

If yes, I'll have a stab at porting that workflow over next week.

**Comment by lukepearson** [comment]
> @lukepearson @Tomdango whilst this looks good, how do you feel about following the same pattern as the main repo, when we publish to npm when tags are pushed?
> 
> If yes, I'll have a stab at porting that workflow over next week.

Yea makes sense to keep it consistent, I'll close this PR to avoid confusion

**Pull request closed without merging**
